<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientsController; // Renamed from AppointmentController
use App\Http\Controllers\ReceptionistController;
use App\Models\Appointment;
use App\Http\Middleware\RoleMiddleware;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Public route
Route::get('/', [HomeController::class, 'index'])->name('home');

// Authenticated routes
Route::middleware('auth')->group(function () {

    // Profile routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Dashboard - shows patient appointments for the logged-in user
    Route::get('/dashboard', function () {
        $appointments = Appointment::where('patient_id', Auth::id())->latest()->get();
        return view('dashboard', compact('appointments'));
    })->name('dashboard');

    /*
    |--------------------------------------------------------------------------
    | Patient Routes
    |--------------------------------------------------------------------------
    */
    Route::middleware([RoleMiddleware::class . ':patient'])->group(function () {
        // Resource controller for patient appointments
        Route::resource('appointments', PatientsController::class);
    });

    /*
    |--------------------------------------------------------------------------
    | Receptionist Routes
    |--------------------------------------------------------------------------
    */
    Route::middleware([RoleMiddleware::class . ':receptionist'])->group(function () {
        // Manage all pending appointments
        Route::get('/receptionist/manage', [ReceptionistController::class, 'manage'])->name('appointments.manage');

        // Accept or decline appointments
        Route::post('/receptionist/{id}/accept', [ReceptionistController::class, 'accept'])->name('appointments.accept');
        Route::post('/receptionist/{id}/decline', [ReceptionistController::class, 'decline'])->name('appointments.decline');
    });
});

// Include auth routes generated by Laravel Breeze/Jetstream
require __DIR__.'/auth.php';
